### PR TITLE
Update group participants

### LINKED ISSUE #324: Update a batch of group participants dosen't work
UpdateGroupParticipants(jid types.JID, participantChanges map[types.JID]ParticipantChange)
 When **participantChanges** map having one participant its works fine, but if more than 1 it's not working returning timeout error .

### PR DESCRIPTION
**Pull request by arugaz**
Fixes #324

### CODE REVIEW

**Comment by arugaz** [comment]
This PR will replace #421

**Comment by arugaz** [comment]
@tulir what do you think? `UpdateGroupParticipants` will break the old function

**Comment by arugaz** [comment]
Closes #441, Closes #462

**Comment by tulir** [comment]
Should definitely break it since the old one doesn't work properly

**Comment by arugaz** [comment]
@tulir could you please merge this, is there anything i need to change?

**Review by tulir — APPROVED** [review]
I changed it to reuse `types.GroupParticipant` and parse the AddRequest properly, otherwise looked good already

**Pull request merged**
