### PR TITLE
Handling WhatsApp Business Messages

### PR DESCRIPTION
**Pull request by hrizal**

### CODE REVIEW

**Comment by tulir** [comment]
That XML parsing feels really hacky since `XMLString` is only meant for debugging. Would be nice to have custom unmarshaling directly from `*waBinary.Node` to arbitrary structs, but that's probably a lot of work :thinking:

**Comment by Diden05** [comment]
@hrizal And why did they close the PR? Everything works!

**Comment by hrizal** [comment]
Ok then

**Comment by hrizal** [comment]
need adjusment ...

**Comment by Diden05** [comment]
@hrizal The rest of the functions are interesting, working with the catalog (create / update / delete) the product, send the product and the collection.
Is a sequel planned?

**Pull request closed without merging**
